FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:353 in lock_release(): assertion `lock->holder->failed_lock == lock' failed.
Call stack: 0x80042180c3 0x800420a725 0x8004213831 0x800421fdc8 0x800421f36a 0x800421f43a 0x800421ddba 0x800421c31d 0x800421bf4b 0x800421d1e7 0x800421d796 0x800421d084
Translation of call stack:
0x00000080042180c3: debug_panic (lib/kernel/debug.c:32)
0x000000800420a725: lock_release (threads/synch.c:354)
0x0000008004213831: disk_read (devices/disk.c:227)
0x000000800421fdc8: inode_read_at (filesys/inode.c:215)
0x000000800421f36a: lookup (filesys/directory.c:88 (discriminator 1))
0x000000800421f43a: dir_lookup (filesys/directory.c:112)
0x000000800421ddba: filesys_open (filesys/filesys.c:87)
0x000000800421c31d: load (userprog/process.c:440)
0x000000800421bf4b: process_exec (userprog/process.c:253)
0x000000800421d1e7: exec (userprog/syscall.c:51)
0x000000800421d796: syscall_handler (userprog/syscall.c:165)
0x000000800421d084: no_sti (syscall-entry.o:?)
